### ISSUE TITLE
The API call failed due to an unexpected HTTP error: Found

### ISSUE THREAD

**Issue by devaiya86** [campaignmonitor/createsend-java#22]
Hi I am trying to execute your sample but it is giving error "The API call failed due to an unexpected HTTP error: Found"

ApiKeyAuthenticationDetails auth = new ApiKeyAuthenticationDetails("API Key");
		 General general = new General(auth);
		 ClientBasics[] clients = general.getClients();
		 System.out.println(clients.toString());

I tried to debug app and found that general.getClients() is throwing error while getting resource.get(klass) in JerseyClientImpl class -> get() implementation.
Please help to resolve this issue.

**Comment by mjwills** [comment]
Sorry to hear you are having issues.

For the "API Key" did you replace it with your account API key?

http://help.campaignmonitor.com/topic.aspx?t=206

**Comment by devaiya86** [comment]
Thanks mjwills. Yes I have replaced my account API key. In details I am getting this error "com.sun.jersey.api.client.UniformInterfaceException: GET http://api.createsend.com/api/v3.1/clients.json returned a response status of 302 Found"  then wrapper overrides exception message with "The API call failed due to an unexpected HTTP error: Found"

**Comment by itgoeslikethis** [comment]
Hi @devaiya86 - the error you're seeing is due to a HTTP 302 response. Which is surprising, because it's one of the standard redirects, but we don't tend to send 302 responses to API requests.

It would be good to know if you can get that API key working without the java wrapper. If you hit this route in the browser: http://api.createsend.com/api/v3.1/clients.json, it'll ask you for a username and password. Put your ApiKey as the username and leave the password blank, what happens? Does it list your clients or do something else?

**Comment by devaiya86** [comment]
Hi Phil Gilmore, I tried  http://api.createsend.com/api/v3.1/clients.json in browser as well REST client. In both way it is working perfect. When I am trying call campaign monitor api from wrapper then only it is giving error. Let me share the steps which i have followed to execute wrapper.

1. Downloaded wrapper from http://campaignmonitor.github.io/createsend-java/
2. Import this project into eclipse and set classpath for jar files mention in pom.xml
3. In SampleRunner.java replace auth with APIKey
4. Run SampleRunner.java

For your reference I have used same jar version which is mentioned in pom.xml.I have downloaded all jars from maven. As per my understanding there is no extra setup required. I am using jdk1.8.0_25. 
Is there anything I did wrong or missed out?

**Comment by richardbremner** [comment]
Hi @devaiya86. I just tried a clean download/build/test and I was unable to reproduce this problem, however I did spot a couple of things that may help.

(1)
The API base url is configured in /src/com.createsend/util/config.properties as:

createsend.endpoint = http://api.createsend.com/api/v3/

This should probably be https:

createsend.endpoint = https://api.createsend.com/api/v3/

It is possible you are being redirected to https, although this didn't happen for me. I expect we will change this via pull request to be https soon.

(2)
Your local environment may somehow be causing a redirect. I notice this line in JerseyClientImpl:

client.setFollowRedirects(false);

If you have some kind of network setup causing redirects, you could try changing this to true.

Please let me know if this is helpful for you.

**Comment by devaiya86** [comment]
Thanks Richard. There were some issue of proxy in my network. I am able to execute CM wrapper from other network.

**Comment by Babavalichetlu** [comment]
Hi I am trying to execute your sample but it is giving error "The API call failed due to an unexpected HTTP error: Found"

ApiKeyAuthenticationDetails auth = new ApiKeyAuthenticationDetails("API Key");

and am running only subscribe method.
runSubscriberMethods(clientID);
code snippet:

SubscriberToAdd subscriber = new SubscriberToAdd();
        subscriber.ListID="65D597D7F9608273";       
        subscriber.EmailAddress = "123@email.com";
        subscriber.Name = "JavaTest";
        subscriber.CustomFields = new CustomField[] {
            new CustomField()
        };
       subscriber.CustomFields[0].Key = "website";
       subscriber.CustomFields[0].Value = "http://www.example.com";
       subscriber.Resubscribe = true;
       subscriber.RestartSubscriptionBasedAutoresponders=true;
        
        System.out.printf("Result of subscriber add: %s\n", subscriberAPI.add(subscriber));

And am getting error like this:

****SubscriberToAdd--{ ListID: 65D597D7F9608273, EmailAddress: 123@email.com, Name: JavaTest,Resubscribe: true,RestartSubscriptionBasedAutoresponders: true }
##### Client Impl starts--line no 260--
resource else part--line no 262--https://api.createsend.com/api/v3.1/subscribers/3e197011dedd7b0bf10c582dae7b126c.json
line no 422-- jerseyclient impl--null
com.createsend.util.exceptions.CreateSendHttpException: The API call failed due to an unexpected HTTP error: Unauthorized
	at com.createsend.util.JerseyClientImpl.handleUnknownError(JerseyClientImpl.java:439)
	at com.createsend.util.JerseyClientImpl.handleErrorResponse(JerseyClientImpl.java:430)
	at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:278)
	at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:244)
	at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:210)
	at com.createsend.Subscribers.add(Subscribers.java:83)
	at com.createsend.samples.SampleRunner.runSubscriberMethods(SampleRunner.java:160)
	at com.createsend.samples.SampleRunner.main(SampleRunner.java:90)
---------------------------------------------------------------------------------------------
i tried this url:GET http://api.createsend.com/api/v3.1/clients.json
response is :[{"ClientID":"MyAccount API key","Name":"Myaccount name"}]
-----------------------------------------------------------------------------------------------
And i changed:
createsend.endpoint = https://api.createsend.com/api/v3.1/ 
In my local environment  JerseyClientImpl:
client.setFollowRedirects(false);

Can any one please help me out 
babavali.chetlu@gmail.com

**Comment by Babavalichetlu** [comment]
HI I got resolved the above issue....
